name = "StarTIN"
uuid = "152385ed-0447-47b3-b417-bbbf3d580ece"
authors = ["Maarten Pronk <git@evetion.nl> and contributors"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
